version: '3'
volumes:
  dados:
networks: 
  dados:
  worker:
  proxy:
services:
  db: 
    image: mongo:3.4
    volumes: 
      - dados:/var/lib/mongo/data
    networks: 
      - dados
  nginx:
    image: nginx
    volumes: 
      - ./nginx/quiz.conf:/etc/nginx/conf.d/quiz.conf
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/quiz.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports: 
      - 80:80
    networks: 
      - proxy
      - worker
  frontend: 
    build: ./frontend
    volumes: 
      - ./frontend:/frontend
      - /frontend/node_modules
    ports: 
      - 3000:3000
    command: npm start
    networks: 
      - proxy
      - worker
      - dados
    depends_on: 
      - db
      - nginx
  backend: 
    build: ./backend
    volumes: 
      - ./backend:/backend
      - /backend/node_modules
    ports: 
      - 3001:3001
    command: npm start
    networks: 
      - proxy
      - worker
      - dados
    depends_on: 
      - db
      - nginx
